name: final_academic_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  firebase_app_check: ^0.3.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
